In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('../data/raw/amazon_sales.csv')

C:\Users\faymu\AppData\Local\Temp\ipykernel_31940\354223964.py:1: DtypeWarning: Columns (0: Unnamed: 22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('../data/raw/amazon_sales.csv')

In [5]:
df

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
0,0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,...,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship,NaN
1,1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,...,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
2,2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,...,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN,NaN
3,3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,...,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False,Easy Ship,NaN
4,4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,...,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128970,128970,406-6001380-7673107,05-31-22,Shipped,Amazon,Amazon.in,Expedited,JNE3697,JNE3697-KR-XL,kurta,...,INR,517.00,HYDERABAD,TELANGANA,500013.0,IN,NaN,False,NaN,False
128971,128971,402-9551604-7544318,05-31-22,Shipped,Amazon,Amazon.in,Expedited,SET401,SET401-KR-NP-M,Set,...,INR,999.00,GURUGRAM,HARYANA,122004.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False
128972,128972,407-9547469-3152358,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0157,J0157-DR-XXL,Western Dress,...,INR,690.00,HYDERABAD,TELANGANA,500049.0,IN,NaN,False,NaN,False
128973,128973,402-6184140-0545956,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0012,J0012-SKD-XS,Set,...,INR,1199.00,Halol,Gujarat,389350.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False
128974,128974,408-7436540-8728312,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0003,J0003-SET-S,Set,...,INR,696.00,Raipur,CHHATTISGARH,492014.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False

In [6]:
df=df.rename(
    columns={
                'Order ID': 'order_id', 
                'Date': 'date',
                'Status': 'status',
                'Fulfilment': 'fulfilment',
                'Sales Channel ': 'sales_channel',
                'ship-service-level': 'ship_service_level',
                'Style': 'style',
                'SKU': 'sku',
                'Category': 'category',
                'Size': 'size',
                'ASIN': 'asin',
                'Courier Status': 'courier_status', 
                'Qty': 'quantity_ordered',
                'Currency': 'currency',
                'Amount': 'amount',
                'ship-city': 'ship_city',
                'ship-state': 'ship_state',
                'ship-postal-code': 'ship_postal_code',
                'ship-country': 'ship_country',
                'promotion-ids':'promotion_ids',
                'B2B':'b2b',
                'fulfilled-by':'fulfilled_by',        
             }, 
    )

In [7]:
df['date']= pd.to_datetime(df['date'], errors='coerce')

C:\Users\faymu\AppData\Local\Temp\ipykernel_31940\2385457312.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['date']= pd.to_datetime(df['date'], errors='coerce')

In [8]:
df = df.drop_duplicates()

In [9]:
df = df.drop(columns=['index'])

In [10]:
df['fulfilled_by']= df['fulfilled_by'].fillna('Unknown')

In [11]:
df['promotion_ids']= df['promotion_ids'].fillna('None')

In [12]:
df['currency'] = df['currency'].fillna('Undefined')

In [13]:
df['amount'] = df['amount'].fillna(0)

In [14]:
df.isna().sum()

order_id                  0
date                      0
status                    0
fulfilment                0
sales_channel             0
ship_service_level        0
style                     0
sku                       0
category                  0
size                      0
asin                      0
courier_status         6872
quantity_ordered          0
currency                  0
amount                    0
ship_city                33
ship_state               33
ship_postal_code         33
ship_country             33
promotion_ids             0
b2b                       0
fulfilled_by              0
Unnamed: 22           49050
dtype: int64

In [15]:
df['Unnamed: 22']

0           NaN
1           NaN
2           NaN
3           NaN
4           NaN
          ...
128970    False
128971    False
128972    False
128973    False
128974    False
Name: Unnamed: 22, Length: 128975, dtype: object

In [16]:
df['Unnamed: 22'].value_counts()

Unnamed: 22
False    79925
Name: count, dtype: int64

In [17]:
df = df.drop(columns=['Unnamed: 22'])

In [18]:
df[df['ship_city'].isna()]

,order_id,date,status,fulfilment,sales_channel,ship_service_level,style,sku,category,size,...,quantity_ordered,currency,amount,ship_city,ship_state,ship_postal_code,ship_country,promotion_ids,b2b,fulfilled_by
1871,404-0566904-4825137,2022-04-29,Shipped,Amazon,Amazon.in,Expedited,J0301,J0301-TP-L,Top,L,...,1,INR,493.0,NaN,NaN,NaN,NaN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,Unknown
1872,404-0566904-4825137,2022-04-29,Shipped,Amazon,Amazon.in,Expedited,JNE3697,JNE3697-KR-L,kurta,L,...,1,INR,458.0,NaN,NaN,NaN,NaN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,Unknown
8752,406-4003386-8768363,2022-04-25,Shipped,Amazon,Amazon.in,Expedited,JNE3376,JNE3376-KR-M,kurta,M,...,1,INR,432.0,NaN,NaN,NaN,NaN,None,False,Unknown
11215,402-0107720-7057168,2022-04-23,Shipped,Amazon,Amazon.in,Expedited,J0003,J0003-SET-S,Set,S,...,1,INR,654.0,NaN,NaN,NaN,NaN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,Unknown
13252,407-4532637-8415521,2022-04-22,Cancelled,Merchant,Amazon.in,Standard,JNE3405,JNE3405-KR-S,kurta,S,...,0,INR,380.0,NaN,NaN,NaN,NaN,None,False,Easy Ship
15688,404-9229894-8608305,2022-04-21,Shipped,Amazon,Amazon.in,Expedited,JNE3510,JNE3510-KR-M,kurta,M,...,1,INR,442.0,NaN,NaN,NaN,NaN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,Unknown
16787,402-4919636-4333150,2022-04-20,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE1233,JNE1233-BLUE-KR-031-XXXL,kurta,3XL,...,1,INR,376.0,NaN,NaN,NaN,NaN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship
18351,405-4927647-8064368,2022-04-19,Shipped,Amazon,Amazon.in,Expedited,J0230,J0230-SKD-XS,Set,XS,...,1,INR,1112.0,NaN,NaN,NaN,NaN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,Unknown
22930,402-8628677-0457954,2022-04-16,Shipped - Returned to Seller,Merchant,Amazon.in,Standard,J0003,J0003-SET-S,Set,S,...,1,INR,654.0,NaN,NaN,NaN,NaN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship
24986,406-4079063-8291520,2022-04-15,Cancelled,Amazon,Amazon.in,Expedited,JNE3567,JNE3567-KR-XXL,kurta,XXL,...,1,INR,399.0,NaN,NaN,NaN,NaN,None,False,Unknown
30379,404-7506843-7913132,2022-04-12,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,SET350,SET350-KR-NP-L,Set,L,...,1,INR,1299.0,NaN,NaN,NaN,NaN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship
37963,407-3064376-9158743,2022-04-08,Cancelled,Merchant,Amazon.in,Standard,JNE3567,JNE3567-KR-M,kurta,M,...,0,INR,380.0,NaN,NaN,NaN,NaN,None,False,Easy Ship
37964,407-3064376-9158743,2022-04-08,Cancelled,Merchant,Amazon.in,Standard,JNE3405,JNE3405-KR-S,kurta,S,...,0,INR,380.0,NaN,NaN,NaN,NaN,None,False,Easy Ship
60986,171-3257610-9237139,2022-05-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3365,JNE3365-KR-1052-A-L,kurta,L,...,1,INR,376.0,NaN,NaN,NaN,NaN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship
63040,402-1049475-3611523,2022-05-20,Shipped,Amazon,Amazon.in,Expedited,JNE3739,JNE3739-KR-XXL,kurta,XXL,...,1,INR,459.0,NaN,NaN,NaN,NaN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,Unknown
73675,405-1356730-8598722,2022-05-11,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,SET187,SET187-KR-DH-XL,Set,XL,...,1,INR,699.0,NaN,NaN,NaN,NaN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship
73746,407-4664354-2179554,2022-05-11,Shipped,Amazon,Amazon.in,Expedited,SET374,SET374-KR-NP-M,Set,M,...,1,INR,666.0,NaN,NaN,NaN,NaN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,Unknown
73771,406-7680604-5439529,2022-05-11,Shipped,Amazon,Amazon.in,Expedited,PJNE3607,PJNE3607-KR-4XL,kurta,4XL,...,1,INR,869.0,NaN,NaN,NaN,NaN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,Unknown
73772,406-7680604-5439529,2022-05-11,Shipped,Amazon,Amazon.in,Expedited,PJNE3368,PJNE3368-KR-4XL,kurta,4XL,...,1,INR,869.0,NaN,NaN,NaN,NaN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,Unknown
73911,405-3420451-5230744,2022-05-11,Cancelled,Amazon,Amazon.in,Expedited,SET374,SET374-KR-NP-M,Set,M,...,0,Undefined,0.0,NaN,NaN,NaN,NaN,None,False,Unknown
80011,171-4552355-0255565,2022-05-07,Shipped - Returned to Seller,Merchant,Amazon.in,Standard,SET324,SET324-KR-NP-XL,Set,XL,...,1,INR,607.0,NaN,NaN,NaN,NaN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship
80092,403-2857451-7335536,2022-05-07,Shipped,Amazon,Amazon.in,Expedited,JNE3510,JNE3510-KR-S,kurta,S,...,1,INR,467.0,NaN,NaN,NaN,NaN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,Unknown
80455,171-4691098-8489159,2022-05-06,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,SET183,SET183-KR-DH-M,Set,M,...,1,INR,759.0,NaN,NaN,NaN,NaN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship
84008,405-8605864-8021901,2022-05-04,Shipped - Returned to Seller,Merchant,Amazon.in,Standard,JNE1951,JNE1951-KR-155-XXL,kurta,XXL,...,1,INR,368.0,NaN,NaN,NaN,NaN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship
84757,402-8651786-0683548,2022-05-04,Shipped,Amazon,Amazon.in,Expedited,JNE3690,JNE3690-TU-XL,Top,XL,...,1,INR,487.0,NaN,NaN,NaN,NaN,None,False,Unknown
104201,403-3190636-2013146,2022-06-18,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,J0351,J0351-SET-S,Set,S,...,1,INR,792.0,NaN,NaN,NaN,NaN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship
106498,402-8673941-7883531,2022-06-16,Cancelled,Amazon,Amazon.in,Expedited,JNE3734,JNE3734-KR-XL,kurta,XL,...,0,Undefined,0.0,NaN,NaN,NaN,NaN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,Unknown
124215,405-0340492-2359532,2022-06-04,Cancelled,Amazon,Amazon.in,Expedited,JNE3465,JNE3465-KR-L,kurta,L,...,1,INR,491.0,NaN,NaN,NaN,NaN,None,False,Unknown
124357,405-5884153-9925116,2022-06-04,Shipped,Amazon,Amazon.in,Expedited,JNE3697,JNE3697-KR-L,kurta,L,...,1,INR,486.0,NaN,NaN,NaN,NaN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,Unknown
124358,405-5884153-9925116,2022-06-04,Shipped,Amazon,Amazon.in,Expedited,SET337,SET337-KR-NP-L,Set,L,...,1,INR,874.0,NaN,NaN,NaN,NaN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,Unknown
124359,405-5884153-9925116,2022-06-04,Shipped,Amazon,Amazon.in,Expedited,SET154,SET154-KR-NP-L,Set,L,...,1,INR,832.0,NaN,NaN,NaN,NaN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,Unknown
125385,403-5172380-9787567,2022-06-03,Shipped,Amazon,Amazon.in,Expedited,JNE3366,JNE3366-KR-1053-L,kurta,L,...,1,INR,376.0,NaN,NaN,NaN,NaN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,Unknown
126620,403-4249038-6582716,2022-06-02,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3797,JNE3797-KR-M,Western Dress,M,...,1,INR,735.0,NaN,NaN,NaN,NaN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship

In [19]:
df['ship_city']= df['ship_city'].fillna('Unknown')

In [20]:
df['ship_state']= df['ship_state'].fillna('Unknown')

In [21]:
df['ship_country']= df['ship_country'].fillna('Unknown')

In [22]:
df['ship_postal_code']= df['ship_postal_code'].fillna('Unknown')

In [23]:
df.loc[df['courier_status'].isna(),['courier_status', 'status']]

       courier_status     status
0                 NaN  Cancelled
3                 NaN  Cancelled
23                NaN  Cancelled
29                NaN  Cancelled
83                NaN  Cancelled
...               ...        ...
128762            NaN  Cancelled
128808            NaN  Cancelled
128855            NaN  Cancelled
128875            NaN  Cancelled
128890            NaN  Cancelled

[6872 rows x 2 columns]

In [24]:
df.loc[df['status']=='Cancelled', ['courier_status'] ]

       courier_status
0                 NaN
3                 NaN
8           Cancelled
23                NaN
29                NaN
...               ...
128961      Unshipped
128962      Unshipped
128965      Unshipped
128967      Cancelled
128969      Unshipped

[18332 rows x 1 columns]

In [25]:
df['courier_status']= df['courier_status'].fillna('Unknown')

In [26]:
df.isna().sum()

order_id              0
date                  0
status                0
fulfilment            0
sales_channel         0
ship_service_level    0
style                 0
sku                   0
category              0
size                  0
asin                  0
courier_status        0
quantity_ordered      0
currency              0
amount                0
ship_city             0
ship_state            0
ship_postal_code      0
ship_country          0
promotion_ids         0
b2b                   0
fulfilled_by          0
dtype: int64

In [27]:
df.loc[df['status']=='Cancelled', ['courier_status'] ] = 'Cancelled'

In [28]:
df.loc[df['status']=='Cancelled', ['courier_status'] ]

       courier_status
0           Cancelled
3           Cancelled
8           Cancelled
23          Cancelled
29          Cancelled
...               ...
128961      Cancelled
128962      Cancelled
128965      Cancelled
128967      Cancelled
128969      Cancelled

[18332 rows x 1 columns]

In [29]:
df['ship_state']=df['ship_state'].str.strip()

In [30]:
df['ship_state']=df['ship_state'].str.replace(' ', '_')

In [31]:
df['ship_state']=df['ship_state'].str.upper()

In [32]:
ship_state_map = {
    "NEW_DELHI": "DELHI",
    "DELHI": "DELHI",
    "ORISSA": "ODISHA",
    "AR": "ARUNACHAL_PRADESH",
    "PONDICHERRY": "PUDUCHERRY",
    "RAJSTHAN": "RAJASTHAN",
    "RAJSH THAN": "RAJASTHAN",
    "RAJSHTHAN": "RAJASTHAN",
    "PB": "PUNJAB",
    "RJ": "RAJASTHAN",
    "NL": "NAGALAND",
    "DADRA_AND_NAGAR": "DADRA_&_NAGAR_HAVELI"
}

df['ship_state'] = df['ship_state'].replace(ship_state_map).str.capitalize()

In [33]:
df['ship_state']= df['ship_state'].str.split('/').str[0]

In [34]:
df = df[df['ship_state'] != 'APO']

In [35]:
df['ship_state'].unique()

array(['Maharashtra', 'Karnataka', 'Puducherry', 'Tamil_nadu',
       'Uttar_pradesh', 'Chandigarh', 'Telangana', 'Andhra_pradesh',
       'Rajasthan', 'Delhi', 'Haryana', 'Assam', 'Jharkhand',
       'Chhattisgarh', 'Odisha', 'Kerala', 'Madhya_pradesh',
       'West_bengal', 'Nagaland', 'Gujarat', 'Uttarakhand', 'Bihar',
       'Jammu_&_kashmir', 'Punjab', 'Himachal_pradesh',
       'Arunachal_pradesh', 'Manipur', 'Goa', 'Meghalaya', 'Tripura',
       'Ladakh', 'Dadra_&_nagar_haveli', 'Sikkim', 'Unknown',
       'Andaman_&_nicobar', 'Mizoram', 'Lakshadweep', 'Apo'], dtype=object)

In [36]:
df['category'].unique()

<StringArray>
[          'Set',         'kurta', 'Western Dress',           'Top',
  'Ethnic Dress',        'Bottom',         'Saree',        'Blouse',
       'Dupatta']
Length: 9, dtype: str

In [37]:
df['category'] = df['category'].str.replace(' ', '_')

In [38]:
df.loc[df['category'].isin(['Western_Dress', 'Ethnic_Dress']) , 'category']

3         Western_Dress
30        Western_Dress
40         Ethnic_Dress
41        Western_Dress
55        Western_Dress
              ...
128960    Western_Dress
128961    Western_Dress
128963    Western_Dress
128964    Western_Dress
128972    Western_Dress
Name: category, Length: 16659, dtype: str

In [39]:
df['category'] = df['category'].str.capitalize()

In [40]:
df

,order_id,date,status,fulfilment,sales_channel,ship_service_level,style,sku,category,size,...,quantity_ordered,currency,amount,ship_city,ship_state,ship_postal_code,ship_country,promotion_ids,b2b,fulfilled_by
0,405-8078784-5731545,2022-04-30,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,S,...,0,INR,647.62,MUMBAI,Maharashtra,400081.0,IN,None,False,Easy Ship
1,171-9198151-1101146,2022-04-30,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,Kurta,3XL,...,1,INR,406.00,BENGALURU,Karnataka,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship
2,404-0687676-7273146,2022-04-30,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,Kurta,XL,...,1,INR,329.00,NAVI MUMBAI,Maharashtra,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,Unknown
3,403-9615377-8133951,2022-04-30,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western_dress,L,...,0,INR,753.33,PUDUCHERRY,Puducherry,605008.0,IN,None,False,Easy Ship
4,407-1069790-7240320,2022-04-30,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,3XL,...,1,INR,574.00,CHENNAI,Tamil_nadu,600073.0,IN,None,False,Unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128970,406-6001380-7673107,2022-05-31,Shipped,Amazon,Amazon.in,Expedited,JNE3697,JNE3697-KR-XL,Kurta,XL,...,1,INR,517.00,HYDERABAD,Telangana,500013.0,IN,None,False,Unknown
128971,402-9551604-7544318,2022-05-31,Shipped,Amazon,Amazon.in,Expedited,SET401,SET401-KR-NP-M,Set,M,...,1,INR,999.00,GURUGRAM,Haryana,122004.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,Unknown
128972,407-9547469-3152358,2022-05-31,Shipped,Amazon,Amazon.in,Expedited,J0157,J0157-DR-XXL,Western_dress,XXL,...,1,INR,690.00,HYDERABAD,Telangana,500049.0,IN,None,False,Unknown
128973,402-6184140-0545956,2022-05-31,Shipped,Amazon,Amazon.in,Expedited,J0012,J0012-SKD-XS,Set,XS,...,1,INR,1199.00,Halol,Gujarat,389350.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,Unknown
128974,408-7436540-8728312,2022-05-31,Shipped,Amazon,Amazon.in,Expedited,J0003,J0003-SET-S,Set,S,...,1,INR,696.00,Raipur,Chhattisgarh,492014.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,Unknown

In [41]:
df.dtypes

order_id                         str
date                  datetime64[us]
status                           str
fulfilment                       str
sales_channel                    str
ship_service_level               str
style                            str
sku                              str
category                         str
size                             str
asin                             str
courier_status                   str
quantity_ordered               int64
currency                         str
amount                       float64
ship_city                        str
ship_state                    object
ship_postal_code              object
ship_country                     str
promotion_ids                    str
b2b                             bool
fulfilled_by                     str
dtype: object

In [43]:
df.to_csv('../data/cleaned/amazon_sales_cleaned.csv', index=False)

In [51]:
import sys
sys.path.append('src')
from clean import run_pipeline
# run_pipeline needs to be pointed at the ../data/raw folder
df_cleaned = run_pipeline(input_path='../data/raw/amazon_sales.csv')
print(df_cleaned.info())

c:\Users\faymu\Downloads\ecommerce-analysis\notebooks\../src\clean.py:47: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['date'] = pd.to_datetime(df['date'], errors='coerce')

File saved in: data/cleaned/amazon_sales_cleaned.csv
<class 'pandas.DataFrame'>
Index: 128968 entries, 0 to 128974
Data columns (total 22 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   order_id            128968 non-null  str
 1   date                128968 non-null  datetime64[us]
 2   status              128968 non-null  str
 3   fulfilment          128968 non-null  str
 4   sales_channel       128968 non-null  str
 5   ship_service_level  128968 non-null  str
 6   style               128968 non-null  str
 7   sku                 128968 non-null  str
 8   category            128968 non-null  str
 9   size                128968 non-null  str
 10  asin                128968 non-null  str
 11  courier_status      128968 non-null  str
 12  quantity_ordered    128968 non-null  int64
 13  currency            128968 non-null  str
 14  amount              128968 non-null  float64
 15  ship_city           128968 non-null  str
 16  ship_state          128968 non-null  object
 17  ship_postal_code    128968 non-null  object
 18  ship_country        128968 non-null  str
 19  promotion_ids       128968 non-null  str
 20  b2b                 128968 non-null  bool
 21  fulfilled_by        128968 non-null  str
dtypes: bool(1), datetime64[us](1), float64(1), int64(1), object(2), str(16)
memory usage: 21.8+ MB
None